### ISSUE TITLE
Allow the request body in /mythril/v1/analysis to include a human-friendly tag

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythx-developer-support#4]
Add a field like "tag" to the payload of this post request, so that a user can get information by a human-friendly name instead of a UUID. If that the tag value matches multiple UUIDs, then all results matching that tag would be retrieved.

**Comment by rocky** [comment]
By the way, we sort of have a way to do this via clientToolName now, but the intent is really different. One is for a tool writer for statistics, and the other is for a user for easy access.

**Comment by muellerberndt** [comment]
Migrated to BAH-72.
