### ISSUE TITLE
Include Mythril version used in the analysis in an analysis status

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythx-developer-support#5]
This is tied with https://github.com/ConsenSys/mythril/issues/484 

As stated there, the problem with doing this independently is that either we issue two requests, a version request and the actual analysis request, or we get the version once and reuse that value. In the latter case, that could be brittle and may disallow us from updating mythril without restarting something else. 

Also I should note, that right now it is just the Mythril version, but in the future as we add more tools, we'll need versions for those as well.

**Comment by birdofpreyru** [comment]
Fixed in **v1.0.25**
