### ISSUE TITLE
Add start and finish time to /mythril/v1/analysis/:id/state

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythx-developer-support#7]
@rocky commented on [Sun Aug 12 2018](https://github.com/ConsenSys/mythril-api/issues/21)

Would be nice to include both a start and end time. 

With the two you can get the elapsed time which is also useful to know. So that might be used instead of one of the start/end times. 

Justification for this information:

People like me want to get a sense of how long something took (elapsed time) and that is something the server side can more accurately provide. 

There is a larger issue going on perhaps that I believe that since the API has to have some state, we should reduce the _necessity_  of the client having to have persistent storage. 

If you by this argument that we make more use of the api's persistent store (and some of this will be added as a separate issue), then when listing what analysis have I run, I am probably interested in either the order they were run, or the order they were finished. (Or both).

Note this is related to issue #18 . 

---

@birdofpreyru commented on [Wed Aug 15 2018](https://github.com/ConsenSys/mythril-api/issues/21#issuecomment-413301416)

Better include these into **GET /mythril/v1/analysis/:id**

**Comment by birdofpreyru** [comment]
Fixed in **v1.0.25**
