### ISSUE TITLE
Add endpoint (e.g. GET /analysis) to give list of analysis-report UUID's on file.

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythx-developer-support#8]
Suggesting that somethig like GET https://api.mythril.ai/analysis would list all of the UUIDs on file.

In general, I am pushing for using the API's persistent store more instead of relying on the client side to retain information. 

Problems with the client-side keeping request information and status: 

* requests can be issued independently by several clients using the same API key,
* clients can crash or lose their persistent store
* client have to be less light weight if they have to maintain a persistent store and handle merging results from parallel jobs

This is related to issue #18 . 
In sum, making more use of mythril-api's persistent storage, adds value to mythril-api. 

---

@birdofpreyru commented on [Wed Aug 15 2018](https://github.com/ConsenSys/mythril-api/issues/22#issuecomment-413301803)

Do you mean the listing of analysis excuted by specified user?

---

@rocky commented on [Mon Aug 20 2018](https://github.com/ConsenSys/mythril-api/issues/22#issuecomment-414297355)

This has been moved to mythil-api-support [Issue 6](https://github.com/ConsenSys/mythril-api-support/issues/6) .

**Comment by birdofpreyru** [comment]
Fixed in **v1.0.25** (`GET /analyses`)
