### ISSUE TITLE
Different classes of users and analysis results: read-only, publicly-viewable

### ISSUE THREAD

**Issue by rocky** [ConsenSys/mythx-developer-support#9]
@rocky commented on [Sun Aug 12 2018](https://github.com/ConsenSys/mythril-api/issues/27)

* "Read-only" users would be able to look at contracts within an API key, but not submit any.
* a "public" attribute on an analysis result would allow anyone to look at the results.

**Comment by muellerberndt** [comment]
Migrated to BAH-71
